CREATE SCHEMA IF NOT EXISTS USER_MGMT;

CREATE TABLE USER_MGMT.USERS
(
    USER_ID uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    FNAME VARCHAR(20) NOT NULL,
    LNAME VARCHAR(20) DEFAULT NULL,
    DOB DATE NOT NULL
    
);

ALTER TABLE USER_MGMT.USERS ADD COLUMN PWD VARCHAR(255) NOT NULL;

CREATE TABLE USER_MGMT.USER_COMMUNICATIONS
(
    USER_ID uuid NOT NULL,
    COMMUNICATION_TYPE VARCHAR(10) NOT NULL,
    VALUE VARCHAR(20) NOT NULL,
    CHOOSEN_TO_COMMUNICATE BOOLEAN DEFAULT FALSE

);


ALTER TABLE USER_MGMT.USER_COMMUNICATIONS ADD CONSTRAINT PK_USR_CTYPE PRIMARY KEY(USER_ID,COMMUNICATION_TYPE);

CREATE TABLE USER_MGMT.USER_PREF
(
    USER_ID uuid NOT NULL,
    PREF_TYPE VARCHAR(20) NOT NULL,
    VALUE VARCHAR(20) NOT NULL

);


ALTER TABLE USER_MGMT.USER_COMMUNICATIONS ADD CONSTRAINT PK_USR_CTYPE PRIMARY KEY(USER_ID,COMMUNICATION_TYPE);

ALTER TABLE USER_MGMT.user_communications ADD CONSTRAINT FK_USR_USERCM FOREIGN KEY(USER_ID) REFERENCES USER_MGMT.USERS(USER_ID);


CREATE TABLE USER_MGMT.USER_AUTH
(
    USER_ID uuid PRIMARY KEY,
    AUTH_MODE VARCHAR(30) DEFAULT 'PWD',
    TWO_FACTOR_ENABLED BOOLEAN DEFAULT FALSE,
    RESET_PWD_ON_FIRST_LOGIN BOOLEAN DEFAULT TRUE,
    PWD VARCHAR(255) DEFAULT NULL
)

ALTER TABLE USER_MGMT.USERS ADD CONSTRAINT fk_user_auth FOREIGN KEY(USER_ID) REFERENCES USER_MGMT.USER_AUTH(USER_ID);

CREATE TABLE USER_MGMT.USER_SESSION
(
    USER_ID uuid NOT NULL,
    SESSION_ID uuid DEFAULT gen_random_uuid() ,
    START_TIME timestamp NOT NULL,
    END_TIME  timestamp 
)