CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS USER_MGMT;

CREATE TABLE USER_MGMT.USERS
(
    USER_ID uuid DEFAULT gen_random_uuid() PRIMARY KEY,
	PWD VARCHAR(20) NOT NULL,
    FNAME VARCHAR(20) NOT NULL,
    LNAME VARCHAR(20) DEFAULT NULL,
    DOB DATE NOT NULL,
	ADDRESSLINE1 VARCHAR(40) NOT NULL,
	ADDRESSLINE2 VARCHAR(40) DEFAULT NULL,
	CITY VARCHAR(20) NOT NULL,
	ZIPCODE VARCHAR(20) NOT NULL,
	AUTHMODE VARCHAR(20)
	);

CREATE TABLE USER_MGMT.USER_COMMUNICATIONS
(
    USER_ID uuid NOT NULL,
    COMMUNICATION_TYPE VARCHAR(10) NOT NULL,
    VALUE VARCHAR(20) NOT NULL,
    CHOOSEN_TO_COMMUNICATE BOOLEAN DEFAULT FALSE

);
ALTER TABLE USER_MGMT.USER_COMMUNICATIONS ADD CONSTRAINT UQ_CTYPE UNIQUE(COMMUNICATION_TYPE,USER_ID)
ALTER TABLE USER_MGMT.USER_COMMUNICATIONS ADD CONSTRAINT fk_user FOREIGN KEY (USER_ID) REFERENCES USER_MGMT.USERS(USER_ID) ON DELETE CASCADE


CREATE TABLE USER_MGMT.USER_PREF
(
    USER_ID uuid NOT NULL,
    PREF_TYPE VARCHAR(20) NOT NULL,
    VALUE VARCHAR(20) NOT NULL

);

ALTER TABLE USER_MGMT.USER_PREF ADD CONSTRAINT fk_user_pref FOREIGN KEY (USER_ID) REFERENCES USER_MGMT.USERS(USER_ID) ON DELETE CASCADE

CREATE TABLE USER_MGMT.USER_AUTH
(
    USER_ID uuid PRIMARY KEY,
    AUTH_MODE VARCHAR(30) DEFAULT 'PWD',
    TWO_FACTOR_ENABLED BOOLEAN DEFAULT FALSE,
    RESET_PWD_ON_FIRST_LOGIN BOOLEAN DEFAULT TRUE,
    PWD VARCHAR(255) DEFAULT NULL
);

ALTER TABLE USER_MGMT.USERS ADD CONSTRAINT fk_user_auth FOREIGN KEY(USER_ID) REFERENCES USER_MGMT.USER_AUTH(USER_ID);
ALTER TABLE USER_MGMT.USERS
DROP CONSTRAINT fk_user_auth;
ALTER TABLE USER_MGMT.USER_AUTH ADD CONSTRAINT fk_user_auth FOREIGN KEY (USER_ID) REFERENCES USER_MGMT.USERS(USER_ID) ON DELETE CASCADE


CREATE TABLE USER_MGMT.USER_SESSION
(
    USER_ID uuid NOT NULL,
    SESSION_ID uuid DEFAULT gen_random_uuid() ,
    START_TIME timestamp NOT NULL,
    END_TIME  timestamp 
);

ALTER TABLE USER_MGMT.USER_SESSION ADD CONSTRAINT fk_user_session FOREIGN KEY (USER_ID) REFERENCES USER_MGMT.USERS(USER_ID) ON DELETE CASCADE
	
    
