CREATE SCHEMA IF NOT EXISTS INVENTORY;

CREATE TABLE INVENTORY.SKU
(
    SKU_ID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    SKU_NAME VARCHAR(100) NOT NULL,
    SKU_DESC VARCHAR(255) NOT NULL,
    SKU_CATEGORY UUID NOT NULL,
    SKU_BRAND UUID NOT  NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
    
);

CREATE TABLE INVENTORY.CATEGORY
(
    CAT_ID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    CAT_NAME VARCHAR(40) NOT NULL,
    CAT_DESC VARCHAR(100) DEFAULT NULL
    
);

ALTER TABLE INVENTORY.SKU ADD CONSTRAINT FK_CAT_SKU FOREIGN KEY(SKU_CATEGORY) 
REFERENCES INVENTORY.CATEGORY(CAT_ID);


CREATE TABLE INVENTORY.SKU_BRAND
(
    BRAND_ID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    BRAND_NAME VARCHAR(40) NOT NULL,
    BRAND_DESC VARCHAR(100) DEFAULT NULL
    
);

ALTER TABLE INVENTORY.SKU ADD CONSTRAINT FK_CAT_BRNAD FOREIGN KEY(SKU_BRAND) 
REFERENCES INVENTORY.SKU_BRAND(BRAND_ID);

ALTER TABLE INVENTORY.SKU ADD COLUMN SELLER UUID NOT NULL;


CREATE TABLE INVENTORY.SELLER(
	SELLER_ID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	FNAME VARCHAR(60) NOT NULL,
	LNAME VARCHAR(60) NOT NULL,
	MOBILE VARCHAR(15) NOT NULL,
	ADDRESS VARCHAR(60) NOT NULL
)

ALTER TABLE INVENTORY.SKU ADD CONSTRAINT FK_CAT_SELLER FOREIGN KEY(SELLER) 
REFERENCES INVENTORY.SELLER(SELLER_ID);

ALTER TABLE inventory.SKU
RENAME COLUMN seller TO seller_id;