name: Create User Management Artifact
on: workflow_dispatch
jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: Clone The Code
        uses: actions/checkout@v4
        with:
          ref: usermanagement
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Deps
        run: pip install -r requirements.txt
      - name: Run Pytest
        run: pytest
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: User_Mgmt_${{github.run_id}}.zip
          path: .
      
  
